spring:
  application:
    name: urbaneye-backend

server:
  port: ${PORT:8080}

firebase:
  bucket-name: urbaneye-ai.appspot.com

gcp:
  project-id: UrbanEye-AI
  location: us-central1

gemini:
  api-key: ${GEMINI_API_KEY}
