spring:
  application:
    name: urbaneye-backend

server:
  port: 8080

firebase:
  bucket-name: urbaneye-ai.appspot.com

gcp:
  project-id: UrbanEye-AI
  location: us-central1

gemini:
 api-key: AQ.Ab8RN6IFv_XS0rqClMmA3s3OXwE_fvASbfwRJZGBI-e1LsZNkQ